// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/skool-map/CommunityDetail.tsx": () => import("../components/mockups/skool-map/CommunityDetail.tsx"),
  "./components/mockups/skool-map/Directory.tsx": () => import("../components/mockups/skool-map/Directory.tsx"),
  "./components/mockups/skool-map/PublicMap.tsx": () => import("../components/mockups/skool-map/PublicMap.tsx"),
  "./components/mockups/skool-map/RadarWorkspace.tsx": () => import("../components/mockups/skool-map/RadarWorkspace.tsx")
};
